services:
  db:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'NHibernateDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
